[book]
title = "Software Engineering Fundamentals"
authors = ["Timo Betcke", "Matthew Scroggs", "Sam Cunliffe", "David Pérez-Suárez", "Monika Byrne Svata", "Paddy Roddy", "Patrick Roddy", "Stephen Thompson", "William Graham"]
language = "en"
src = "src"
